# -*- coding: utf-8 -*-
"""LVADSUSR85_Sravanthi_fal2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G0xRsDfDqXHPWo6vRUJbfAZJiiWpo6uy
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,mean_squared_error,r2_score

data = pd.read_csv('/content/auto-mpg.csv')
df = pd.DataFrame(data)
print(df.isnull().sum(),end='\n\n')
print(df.info())
print(df)

#df['horsepower'].astype(integer)
df.fillna(df['displacement'].mean(),inplace=True)
df.fillna(df['horsepower'].mode(),inplace=True)
df.isnull().sum()

le = LabelEncoder()
df['car name'] = le.fit_transform(df['car name'])

sns.heatmap(df.corr())
plt.show()

features = df[['origin','model year','acceleration','cylinders','displacement','weight','car name']]
labels = df['mpg']
x_train,x_test,y_train,y_test = train_test_split(features,labels,test_size=0.3)
model = LinearRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
mse = mean_squared_error(y_test,y_pred)
rmse = mean_squared_error(y_test,y_pred,squared = False)
r2 = r2_score(y_test,y_pred)
print(mse,rmse,r2)

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, color='blue')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], color='red', linestyle='--')
plt.xlabel('True Values')
plt.ylabel('Predicted Values')
plt.title('Scatter Plot of True vs Predicted Values')
plt.show()