# -*- coding: utf-8 -*-
"""LVADSUSR85_Sravanthi_ia2lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EsWM8QRhfphvPdGsChWFuQlbMJZtjj-S
"""

import pandas as pd
data = pd.read_csv("/content/Mall_Customers.csv")
df = pd.DataFrame(data)

df['Annual Income (k$)'].fillna(df['Annual Income (k$)'].ffill(),inplace = True)
df.isnull().sum()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

X = df[['Age','Annual Income (k$)']]
y = df['Spending Score (1-100)']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state=0)

from sklearn.preprocessing import Normalizer
normalizer = Normalizer()
nx = normalizer.fit_transform(x_train)
ny = normalizer.fit_transform(x_test)

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
inertia =[]
for i in range(1,11):
  kmeans = KMeans(n_clusters=i)
  kmeans.fit(x_train)
  inertia.append(kmeans.inertia_)

plt.plot(range(1,11),inertia,marker='o')

import seaborn as sns
kmeans = KMeans(n_clusters=2)
kmeans.fit(nx)
sns.scatterplot(data = x_train,x='Age',y='Annual Income (k$)',hue=kmeans.labels_)
plt.plot()

from sklearn.metrics import silhouette_score,davies_bouldin_score,calinski_harabasz_score

silhouette_score = silhouette_score(df, y)
davies_bouldin_score = davies_bouldin_score(df, y)
calinski_harabasz_score = calinski_harabasz_score(df, y)

print(silhouette_score)
print(davies_bouldin_score)
print(calinski_harabasz_score)