# -*- coding: utf-8 -*-
"""LVADSUSR85_Sravanthi_lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hvLaimQQGMbpR-4yXhe8BIue5ZVwx6D5
"""

#1

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#from sklearn.metrics import stats

df = pd.read_csv('/content/expenses.csv')

print(df.describe(),end='\n\n')
print(df.info(),end='\n\n')
print(df.isnull().sum(),end='\n\n')

plt.boxplot(df['bmi'])
plt.show()

plt.boxplot(df['charges'])
plt.show()

Q1 = df['charges'].quantile(0.25)
Q3 = df['charges'].quantile(0.75)
IQR = Q3 - Q1
lower_limit = Q1 - (1.5*IQR)
upper_limit = Q3 + (1.5*IQR)
df = df[~(df['charges'] < lower_limit) | (df['charges'] > upper_limit)]

Q1 = df['bmi'].quantile(0.25)
Q3 = df['bmi'].quantile(0.75)
IQR = Q3 - Q1
lower_limit = Q1 - (1.5*IQR)
upper_limit = Q3 + (1.5*IQR)
df = df[~(df['bmi'] < lower_limit) | (df['bmi'] > upper_limit)]

import seaborn as sns

sns.heatmap(df.corr(),annot=True)

#2

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['smoker'] = le.fit_transform(df['smoker'])
df['region'] = le.fit_transform(df['region'])

print(df.head(20))

#3

features = df[['sex','age','bmi','children','smoker','region']]
labels = df['charges']

df.duplicated().sum()
df.drop_duplicates()

#4

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(features,labels,test_size=0.3)

#5

from sklearn.linear_model import LinearRegression

clf = LinearRegression()
clf = clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)

#6

from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
print("mean squared error: ",mse)
rmse = np.sqrt(mse)
print("root mean squared error: ",rmse)
r2 = r2_score(y_test, y_pred)
print("r2 score: ",r2)