# -*- coding: utf-8 -*-
"""LVADSUSR85-Sravanthi-FA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MJfLItrWdp3zaAdNu-XHCmoFvwJcKcBV
"""

#1

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
print(df.info(),end='\n\n')
print(df.head(),end='\n\n')
print(df.tail(),end='\n\n')
print(df.describe(),end='\n\n')

#2

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
#print(pd.isna(df))
print(pd.isna(df).sum(),end='\n\n')
print(df.duplicated().sum())

#3

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
print("sum of sales is ",df['Sales'].sum(),end='\n\n')
print("mean of quantity is ",df['Quantity'].mean(),end='\n\n')
print("median of quantity is ",df['Quantity'].median(),end='\n\n')
print("mode of quantity is ",df['Quantity'].mode(),end='\n\n')
print("variance of profit is ",df['Profit'].var(),end='\n\n')
print("standard deviation of profit is ",df['Profit'].std(),end='\n\n')

#4

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
df = df.head(20)
plt.figure(figsize=(10,6))
plt.bar(df['Order ID'],df['Sales'])
plt.xticks(rotation=45,fontsize=8)
plt.title("bar plot for order id and sales")
plt.xlabel("order id")
plt.ylabel("sales")
plt.show()

#4

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
df = df.head(20)
plt.figure(figsize=(10,6))
plt.pie(df['Profit'],labels = df['Category'])
plt.show()

#4

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
df = df.head(20)
plt.figure(figsize=(5,5))
sns.boxplot(df['Quantity'],color="b")
plt.title("box plot for quantity")
plt.ylabel("quantity")
plt.show()

#5

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
df = df.head(20)
plt.figure(figsize=(10,6))
df = df[['Profit','Sales']]

co = df.corr()
sns.heatmap(co,annot=True)
plt.show()

#6

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
#df = df.head(100)
plt.figure(figsize=(5,5))
sns.boxplot(df['Quantity'],color="b")
plt.title("box plot for quantity")
plt.ylabel("quantity")
plt.show()

"""total of 5 outliers found from this box plot for quantity.
it means they are not in the usual range of buying a product of that quantity.

"""

#7 trend i

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
df = df.head(50)
plt.figure(figsize=(10,6))
df['Sales']=df['Sales'].sort_values()
df['Profit']=df['Profit'].sort_values()
df1 = df[['Order Date','Sales','Profit']]
#plt.plot(df['Order Date'],df['Sales'],marker='o',label='sales')
#plt.plot(df['Order Date'],df['Profit'],marker='s',label='profit')
sns.lineplot(df1,marker='o')
plt.xlabel('date')
plt.ylabel('quantity')
plt.legend()
plt.show()

#7 trend ii

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
df = df.head(10)
df1 = df.groupby('Category')['Sales'].sum()
print(df1)
plt.figure(figsize=(5,5))
plt.pie(df['Sales'],labels=df['Category'])
plt.title("pie chart for category and sales")
plt.show()

#7 customer i

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
df1 = df.groupby('EmailID')['Order ID'].count().sort_values(ascending=False)
df2 = df.groupby('EmailID')['Sales'].sum().sort_values(ascending=False)
fin_df = pd.merge(df1,df2,on='EmailID',how='inner')
print(fin_df.head(5))
fin_df = fin_df.head(10)
sns.lineplot(data = fin_df, x=fin_df['Order ID'] ,y= fin_df['Sales'])
plt.show()

#7 customer ii

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
df1 = df[['Order ID','Profit']]
#sns.pairplot(df1)
#sns.scatterplot(df1)
sns.barplot(df1)
plt.show()

#7 comprehensive i


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
df1 = df[['Sales','Profit']]
#sns.pairplot(df1)
#sns.scatterplot(df1)
sns.barplot(df1)
plt.show()

"""sales is more but profit is very less so
increase the price of products
decrease the quantity of products
increase the marketing level of product
change the strategy of selling a product
"""

#7 comprehensive ii

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
df = df.head(30)
df1 = df.groupby('Geography')['Sales'].sum()
#df1 = df[['Sales','Geography']]
#sns.pairplot(df1)
#sns.scatterplot(df1)
sns.lineplot(df1,marker='o')
plt.xticks(rotation=45,fontsize=8)
plt.show()

"""we can see united states,los angeles, california have higher sales so we can do target marketing here by going deeper into problem like what type of products are the people in this place buying and why?
we can get insights from this
"""

#7 comprehensive iii

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('/content/Walmart_Dataset Python_Final_Assessment.xlsx')
df['cust_name'] = df['EmailID'].astype(str).str.split('@').str[0]
df1 = df.groupby('cust_name')['Order ID'].count().sort_values(ascending=False)
df2 = df.groupby('cust_name')['Sales'].sum().sort_values(ascending=False)
fin_df = pd.merge(df1,df2,on='cust_name',how='inner')
print(fin_df.head(5))
#fin_df = fin_df.head(10)
#sns.lineplot(data = fin_df, x=fin_df['Order ID'] ,y= fin_df['Sales'])
co = fin_df.corr()
sns.heatmap(co,annot=True)
#sns.scatterplot(data=fin_df)
#plt.xlabel("count of order id")
plt.show()