# -*- coding: utf-8 -*-
"""LVADSUSR85-SRAVANTHI-IA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MdXocWQG686rTyr6dqqau7RLm3EX1DhZ
"""

#1

import numpy as np

rgb_image = ([[[255,0,0],[0,255,0],[0,0,255]],
              [[255,255,0],[255,0,255],[0,255,255]],
              [[127,127,127],[200,200,200],[50,50,50]]])

def convertrgb():
  return rgb_image * np.array([0.2989,0.5870,0.1140])

print(convertrgb())

#2

import numpy as np

arr = np.array([[167,67,22],[160,65,23],[157,70,21]])
arr1 = arr/1000
print(arr1)
print("height mean: ",round(np.mean(arr1[0:3,0])))
print("weight mean: ",round(np.mean(arr1[0:3,1])))
print("age mean: ",round(np.mean(arr1[0:3,2])))

print("height standard deviation: ",round((np.std(arr1[0:3,0])*100)+1))
print("weight standard deviation: ",round((np.std(arr1[0:3,1])*100)+1))
print("age standard deviation: ",round((np.std(arr1[0:3,2])*100)+1))

#3

import numpy as np

arr1 = np.array([[1,2],[3,4],[5,6]])
arr2 = np.array([[7,8],[9,10],[11,12]])
print(arr1)
print()
print(arr2)
print()
arr3 = np.concatenate((arr1,arr2))
print(np.array(arr3,ndmin=3))
print()
arr4 = arr3.flatten()
print()
print(arr4)
print()
arr5 = arr4.reshape(6,2)
print(arr5)

#4

import numpy as np

arr = np.array([[10,9,7],[6,8,5],[8,9,10]])
arr1 = arr.argsort().argsort()
print(arr1)
print()
print("performance of athlete 1: ",arr1[0])
print("performance of athlete 2: ",arr1[1])
print("performance of athlete 3: ",arr1[2])

#5

import numpy as np

arr = np.array([[10,9,7,3,-1,9],[6,8,5,-1,8,9],[8,9,10,7,6,9]])
arr1 = arr[0:3,-3::]
print(arr[0:3,-3::])
print()
print(np.where(arr1>0,np.mean((arr[0:3,-3::]),axis=0),0))
#avg = np.mean((arr[0:3,-3::]),axis=0)

#6

import pandas as pd
data={ 'Name': ['Alice','Bob','Charlie'],
      'age': [25,50,35],
       'city':['new york','chicago','los angeles'],
       'dept':['hr','it','finance']
       }
df = pd.DataFrame(data)
df1= df[df['age']<45]
df2 = df[df['dept']!='hr']
print(df1)
print()
print(df2)