# -*- coding: utf-8 -*-
"""python_assessment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wi3TC1-YvROfE1buXHjUND-Vb8DJjgkm
"""

#1

length = float(input("enter length of rectange: "))
width = float(input("enter width of rectangle: "))
area = length * width
print(area)

#2

weight = float(input("enter your weight in kg: "))
height = float(input("enter your height in m: "))
bmi = weight/(height*height)
print(bmi)

#3

student_dict = {'sravanthi':97,'jaswanth':85,'raju':90,'karim':87}
print(student_dict)
print("score of raju is: ",student_dict['raju'])
print()

#add one student details
name = input("enter any student name: ")
score = float(input("enter student's score: "))
student_dict[name]=score
print(student_dict)
print()

#add multiple student details
n = int(input("enter number of students: "))
for _ in range(n):
  name = input("enter any student name: ")
  score = int(input("enter student's score: "))
  student_dict[name]=score
print(student_dict)

#4

age = int(input("enter your age: "))
if(age<18):
  print("minor")
elif(age>=18 and age<=40):
  print("adult")
else:
  print("senior")

#5

for i in range(1,51):
  if(i%2==0):
    print(i, end = ' ')

#6

def enter_pass():
  password = input("enter a password: ")
  if(len(password)>6):
    print("ok")
  else:
    enter_pass()

enter_pass()

#7

def avg_list(l):
  sum=0
  for i in l:
    sum+=i
  return sum/len(l)

lst=[]
n = int(input("enter number of elements: "))
for _ in range(n):
  lst.append(int(input("enter a number: ")))
print(avg_list(lst))

#8

vowels = ['a','e','i','o','u']
cnt=0
string = input("enter any string: ")
for i in string:
  if i in vowels:
    cnt+=1
print("number of vowels:", cnt)

#9

from datetime import date
print(date.today())

#10

try:
  value1 = int(input("enter a value: "))
  value2 = int(input("enter a value: "))
  print(value1+value2)
except:
  print("enter valid values")

#11

def fun():
  try:
    n=int(input())
    print(n)
  except:
    print("value error")

fun()

#12

val1 = 5
val2 = 0
try:
  print(val1/val2)
except ZeroDivisionError:
  print("division by zero error")

#13

f = open("file_2.txt",'w')
f.writelines("Hello Python!")
f.close()

#14

f = open("file_2.txt",'r')
print(f.read())
f.close()

#15
f = open("file_2.txt",'a')
f.writelines(" Python is user friendly ")
f.close()

f = open("file_2.txt",'r')
print(f.read())
f.close()